#!/bin/zsh

authorName=$1
authorEmail=$2

git filter-branch -f --env-filter \
"GIT_AUTHOR_NAME=$authorName; GIT_AUTHOR_EMAIL=$authorEmail; \
GIT_COMMITTER_NAME=$authorName; GIT_COMMITTER_EMAIL=$authorEmail;" HEAD

