customCommands:
  - key: '<c-g>'
    command: "serie"
    context: 'global'
    description: 'Show commit graph'
    output: terminal
  - key: 'x'
    command: "xed --background ."
    context: 'global'
    description: 'Opens Xcode on current project'
    loadingText: 'Opening Xcode on current project'
  - key: 'X'
    context: 'global'
    command: >-
      osascript -e 'quit app "Xcode"' rm -rf "~/Library/Developer/Xcode/DerivedData"
    description: 'Closes Xcode on current project'
    loadingText: 'Closing Xcode on current project'
    #command: "kill $(ps aux | grep 'Xcode' | awk '{print $2}')"
    #command: xed . && osascript -e 'tell app "XCode" to close window 0'
    #command: killall Xcode
  - key: '<c-d>'
    context: 'commits'
    description: 'Change commit date and time'
    prompts:
      - type: 'input'
        title: 'Give a new date and time for the commit (default current timestamp):'
        key: 'CommitTimestamp'
        initialValue: ''
        suggestions:
          command: 'Enter a timestamp using the ISO 8601 format'
    # TODO: Check if a timestamp is being entered otherwise use current timestamp with ISO 8601 format -> `date -Iseconds` but using Go
    command: >-
      echo "{{.SelectedLocalCommit.Hash}}" git rebase --interactive {{.SelectedCommit.Hash}}~1 GIT_AUTHOR_DATE=format:iso8601:\"{{.Form.CommitTimestamp}}\" GIT_COMMITTER_DATE=format:iso8601:\"{{.Form.CommitTimestamp}}\" git commit --amend --no-edit --date \"{{.Form.CommitTimestamp}}\" git rebase --continue
    loadingText: 'Changing commit timestamp'
    output: popup
git:
  autoFetch: true
  autoRefresh: true
  disableForcePushing: false
  fetchAll: true # Pass --all flag when running git fetch. Set to false to fetch only origin (or the current branch's upstream remote if there is one)
  mainBranches: [master, main]
  paging:
    colorArg: always
    pager: delta --true-color=always --paging=never #--24-bit-color=never
    useConfig: false
  # The main branches. We colour commits green if they belong to one of these branches,
  # so that you can easily see which commits are unique to your branch (coloured in yellow)
  parseEmoji: true
gui:
  authorColors:
    # use green for me
    'Pere Bohigas': 'green'
    # use white for other authors
    '*': 'white'
  language: 'en' # one of 'auto' | 'en' | 'zh-CN' | 'zh-TW' | 'pl' | 'nl' | 'ja' | 'ko' | 'ru'
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - reverse
      - bold
  timeFormat: '02 Jan 2006' # https://pkg.go.dev/time#Time.Format
notARepository: 'quit'
os:
  editPreset: 'nvim'
