# run 'brew bundle' to install all listed packages

### Homebrew taps ###
tap "homebrew/bundle"

### Mac App Store CLI ###
brew "mas" # Mac App Store command-line interface

### Fonts ###
# cask "font-hack-nerd-font"
# cask "font-roboto-mono-for-powerline"
cask "font-roboto-mono-nerd-font"
cask "font-commit-mono-nerd-font"

### Version managers ###
brew "mise" # Polyglot runtime manager (asdf rust clone)
brew "nvm" # Manage multiple Node.js versions
brew "pyenv" # Python version management
brew "rbenv" # Ruby version manager

### Shell plugins ###
brew "jandedobbeleer/oh-my-posh/oh-my-posh" # Prompt theme engine for any shell
brew "parallel" # Shell command parallelization utility
# brew "starship" # Cross-shell prompt for astronauts
brew "zoxide" # Shell extension to navigate your filesystem faster
brew "zsh-autosuggestions" # Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-syntax-highlighting" # Fish shell like syntax highlighting for zsh
brew "zsh-vi-mode" # Better and friendly vi(vim) mode plugin for ZSH

### Compilers ###
brew "ghcup" # Installer for the general purpose language Haskell
brew "make" # Utility for directing compilation
brew "pkl" # CLI for the Pkl programming language
brew "rust" # Safe, concurrent, practical language

### Editors ###
brew "neovim" # Ambitious Vim-fork focused on extensibility and agility
cask "zed" # Multiplayer code editor

### Version control ###
cask "fork" # GIT client
brew "git" # Distributed revision control system
brew "git-delta" # Syntax-highlighting pager for git and diff output
brew "git-lfs" # Git extension for versioning large files
brew "gitleaks" # Audit git repos for secrets
brew "gitui" # Blazing fast terminal-ui for git written in rust
cask "gitup" # Git interface focused on visual interaction
brew "hub" # Add GitHub support to git on the command-line
brew "lazygit" # Simple terminal UI for git commands

### File/Memory management ###
brew "duf" # Disk Usage/Free Utility - a better 'df' alternative
brew "dust" # More intuitive version of du in rust
brew "superfile" # Modern and pretty fancy file manager for the terminal
brew "tree" # Display directories as trees (with optional color/HTML output)
brew "yazi" # Blazing fast terminal file manager written in Rust, based on async I/O

### Process/System monitor ###
brew "bottom" # Yet another cross-platform graphical process/system monitor
brew "htop" # Improved top (interactive process viewer)

### VPN ###
# brew "openconnect" # Open client for Cisco AnyConnect VPN

### Networking ###
brew "julien-cpsn/atac/atac" # A simple API client (postman like) in your terminal
brew "curlie" # Power of curl, ease of use of httpie
brew "drill" # HTTP load testing application written in Rust
cask "hoppscotch" # Open source API development ecosystem
# cask "proxyman" # Modern and intuitive HTTP Debugging Proxy app
brew "telnet" # User interface to the TELNET protocol
brew "xh" # Friendly and fast tool for sending HTTP requests

### Virtualization & Containers ###
# cask "balenaetcher" # Tool to flash OS images to SD cards & USB drives -> NOT M1 COMPATIBLE
cask "citrix-workspace" if system(%q[mdfind "kMDItemKind == 'Application'" | grep -q "Endpoint Security VPN\.app$"]) # Managed desktop virtualization solution
# brew "docker" # App to build and share containerized applications and microservices
brew "podman" # Tool for managing OCI containers and pods
cask "raspberry-pi-imager" # Imaging utility to install operating systems to a microSD card -> NOT M1 COMPATIBLE

### Image editing/manipulation ###
cask "drawio" # Draw.io is free online diagram software
cask "gimp" # Free and open-source image editor -> NOT M1 COMPATIBLE
brew "imagemagick" # Tools and libraries to manipulate images in many formats
cask "imageoptim" # Tool to optimize images to a smaller size
cask "inkscape" # Vector graphics editor
brew "viu" # Simple terminal image viewer written in Rust
# cask "zeplin" # Share, organize and collaborate on designs

### Compression ###
cask "keka" # File archiver

### Internet browser ###
cask "brave-browser" # Web browser focusing on privacy
cask "firefox" # Web browser
# Browserpass setup for Firefox:
# PREFIX='/opt/homebrew/opt/browserpass' make hosts-firefox-user -f '/opt/homebrew/opt/browserpass/lib/browserpass/Makefile'
# Browserpass setup for Brave:
# PREFIX='/opt/homebrew/opt/browserpass' make hosts-brave-user -f '/opt/homebrew/opt/browserpass/lib/browserpass/Makefile'
brew "amar1729/homebrew-formulae/browserpass" # Host application for browser extension providing access to your password store
mas "Consent-O-Matic", id: 1606897889

### PDF inspection/manipulation ###
brew "ghostscript" # Interpreter for PostScript and PDF
cask "skim" # PDF reader and note-taking application

### Writing ###
cask "deepl" # Trains AIs to understand and translate texts
mas "LanguageTool", id: 1534275760

### Office tools ###
mas "Keynote", id: 409183694
cask "libreoffice" # Office suite
cask "mactex" # Full TeX Live distribution with GUI applications
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
# cask "zotero" # Collect, organize, cite, and share research sources -> NOT M1 COMPATIBLE

### Keyboard Tools ###
brew "gnu-typist" # GNU typing tutor
mas "Keymapp", id: 6472865291 # ZSA keyboard firmware flasher
brew "toipe" # Yet another typing test, but crab flavoured

### User manual ###
brew "cheat" # Create and view interactive cheat sheets for *nix commands
brew "tldr" # Simplified and community-driven man pages

### File inspection ###
brew "bat" # Clone of cat(1) with syntax highlighting and Git integration
cask "exifcleaner" # Metadata cleaner -> NOT M1 COMPATIBLE
brew "eza" # Modern, maintained replacement for ls
brew "fx" # Terminal JSON viewer
brew "glow" # Render markdown on the CLI
brew "jq" # Lightweight and flexible command-line JSON processor
brew "jql" # JSON query language CLI tool
brew "qpdf" # Tools for and transforming and inspecting PDF files
brew "hexyl" # Command-line hex viewer
brew "tabiew" # TUI to view and query tabular files (CSV,TSV, Parquet, etc.)
brew "tesseract" # OCR (Optical Character Recognition) engine
brew "tesseract-lang" # Enables extra languages support for Tesseract
brew "xq" # Command-line XML and HTML beautifier and content extractor
brew "yq" # Process YAML, JSON, XML, CSV and properties documents from the CLI

### File and content search ###
brew "fd" # Simple, fast and user-friendly alternative to find
brew "fzf" # Command-line fuzzy finder written in Go
brew "ripgrep" # Search tool like grep and The Silver Searcher
brew "sd" # Intuitive find & replace CLI

### Terminal ###
cask "alacritty" # GPU-accelerated terminal emulator
brew "cmatrix" # Console Matrix
cask "ghostty" # Terminal emulator that uses platform-native UI and GPU acceleration
brew "zellij" # Pluggable terminal workspace, with terminal multiplexer as the base feature

### Time management ###
# mas "Be Focused", id: 973134470
# cask "clockify" # Time tracking tool for agencies and freelancers
# cask "michaelvillar-timer" # Timer application

### Password management ###
# cask "1password" # Password manager that keeps all passwords secure behind one password
mas "Bitwarden", id: 1352778147 # Desktop password and login vault
brew "pass" # Password manager
brew "pinentry-mac" # Pinentry for GPG on Mac
# cask "keeweb" # Password manager compatible with KeePass
cask "macpass" # Open-source, KeePass-client and password manager

### Database ###
cask "dbeaver-community" # Universal database tool and SQL client
cask "pgadmin4" # Administration and development platform for PostgreSQL
brew "postgresql@17" # Object-relational database system
brew "rainfrog" # Database management TUI for Postgres

### Note taking ###
# cask "notion" # App to write, plan, collaborate, and get organized
cask "obsidian" # Knowledge base that works on top of a local folder of plain text Markdown files
mas "reMarkable", id: 1276493162 # View, Screen Share, organize, import, and download files to a reMarkable device

### Windows management ###
# cask nikitabobko/tap/aerospace # AeroSpace is an i3-like tiling window manager for macOS
cask "amethyst" # Automatic tiling window manager similar to xmonad
# cask "rectangle" # Move and resize windows using keyboard shortcuts or snap areas
# brew "yabai" # A tiling window manager for macOS based on binary space partitioning

### macOS utilities ###
cask "appcleaner" # Application uninstaller
cask "blackhole-2ch" # Virtual Audio Driver
# cask "blackhole-16ch" # virtual audio driver (internal audio routing)
brew "defaultbrowser" # Command-line tool for getting & setting the default browser
# cask "hammerspoon" # Desktop automation application
cask "leader-key" # Application launcher
cask "maccy" # Clipboard manager
cask "monitorcontrol" # Tool to control external monitor brightness & volume
# noTunes Setup: defaults write digital.twisted.noTunes replacement /Applications/Spotify.app
cask "notunes" # Simple application that will prevent iTunes or Apple Music from launching
# cask "qlmarkdown" # QuickLook generator for Markdown files
cask "shortcat" # App that enables mouse-free UI interaction
# brew "skhd" # Simple hotkey-daemon for macOS

### Learning ###
cask "anki" # Memory training application

### Cloud ###
#cask "google-drive" # Client for the Google Drive storage service
mas "OX Drive", id: 818195014 # Cloud client
#cask "seafile-client" # File syncing client -> NOT M1 COMPATIBLE
cask "syncthing" # Real time file synchronization software

### Messaging/Video call ###
cask "microsoft-teams" # Meet, chat, call, and collaborate in just one place
# cask "mumble" # Open-source, low-latency, high quality voice chat software for gaming
cask "signal" # Instant messaging application focusing on security
mas "Slack", id: 803453959 # Team communication and collaboration software
cask "studiolinkstandalone" # SIP application to create high quality Audio over IP (AoIP) connections
cask "telegram" # Messaging app with a focus on speed and security
mas "WhatsApp", id: 310633997
cask "zoom" # Video communication and virtual meeting platform

### Video creation/playback ###
mas "Gifski", id: 1351639930
cask "handbrake" # Open-source video transcoder
mas "iMovie", id: 408981434
cask "shotcut" # Video editor
cask "vlc" # Multimedia player

### Music creation/playback ###
mas "GarageBand", id: 682658836
cask "sonos" # Control your Sonos system
cask "spotify" # Music streaming service

### Android development ###
cask "jetbrains-toolbox" # JetBrains tools manager
brew "kdoctor" # Environment diagnostics for Kotlin Multiplatform Mobile app development -> Kotlin Multiplatform

### iOS development ###
mas "Apple Configurator", id: 899247664
brew "dependency-check" # OWASP dependency-check
mas "Dev Jobs", id: 1578276279
mas "Developer", id: 640199958 # Apple Developer
# brew "licenseplist" # License list generator of all your dependencies for iOS applications
brew "lizard-analyzer" # Extensible Cyclomatic Complexity Analyzer
brew "mint" # Dependency manager that installs and runs Swift command-line tool packages
cask "sf-symbols" # Tool that provides consistent, highly configurable symbols for apps
# cask "swiftybeaver" # Access your app logs in development & release with end-to-end encryption -> NOT M1 COMPATIBLE
# brew "swiftenv" # Swift version manager
# brew "swiftgen" # Swift code generator for assets, storyboards, Localizable.strings, … -> Installed using Mise
# brew "swiftlint" # Tool to enforce Swift style and conventions -> Installed using Mise
# brew "swift-format" # Formatting technology for Swift source code -> Installed using Mise
brew "swift-protobuf" # Plugin and runtime library for using protobuf with Swift
mas "TestFlight", id: 899247664
# mas "Xcode", id: 497799835 # <- Xcode being installed using xcodes
brew "xcodesorg/made/xcodes" # Best command-line tool to install and switch between multiple versions of Xcode
# cask "xcodesorg/made/xcodes" # Install and switch between multiple versions of Xcode -> App version of xcodes command-line tool
# brew "xcbeautify" # Little beautifier tool for xcodebuild -> Installed using Mise
# brew "xcodegen" # Generate your Xcode project from a spec file and your folder structure -> Installed using Mise
brew "vapor" if system(%q[mdfind "kMDItemKind == 'Application'" | grep -qE "Xcode-[0-9]*\.[0-9]*\.[0-9]*\.app$"]) # Command-line tool for Vapor (Server-side Swift web framework) -> requires Xcode

