## Used to execute commands just after logging in

# Homebrew initialization
[[ -f "/opt/homebrew/bin/brew" ]] && eval "$(/opt/homebrew/bin/brew shellenv)"

# CocoaPods initialization
export LC_ALL=en_US.UTF-8

# JetBrains Toolbox initialization
[[ -d "$HOME/Library/Application Support/JetBrains/Toolbox/scripts" ]] && export PATH="$PATH:$HOME/Library/Application Support/JetBrains/Toolbox/scripts"

