#!/bin/zsh

### Custom defined aliases ###

## ls
if (( $+commands[eza] )); then
	# Show files and directories
	alias l="eza -l --git --group-directories-first --icons --no-user"
	# Show files and directories sorted by recently modified
	alias ld="eza -l --git --group-directories-first --icons --no-user --sort=modified -r"
	# Show files and directories including hidden ones
	alias ll="eza -al --git --group-directories-first --icons --no-user"
	# Show files and directories including hidden ones sorted by recently modified
	alias lld="eza -al --git --group-directories-first --icons --no-user --sort=modified -r"
	# Show files and directories including hidden ones in a three level depth
	alias lll="eza -alT --git --group-directories-first --icons --level=3 --no-user"
	# Show files and directories including hidden ones in a three level depth sorted by recently modified
	alias llld="eza -alT --git --group-directories-first --icons --level=3 --no-user --sort=modified -r"
else
	# Show files and directories
	alias l="ls -FGhl"
	# Show files and directories sorted by recently modified
	alias ld="ls -FGhlt"
	# Show files and directories including hidden ones
	alias ll="ls -aFGhl"
	# Show files and directories including hidden ones sorted by recently modified
	alias lld="ls -aFGhlt"
fi

## cd
alias .="cd ."
alias ..="cd .."

## Navigation
# Personal directories
alias pro="cd $HOME/Developer/Personal_Projects/"
alias doc="cd $HOME/Documents/'OX Drive'/'My files.localized'/Documents.localized/personal_documents"

# ams directories
alias ams="cd $HOME/Developer/AMS_Projects/"
alias amsdoc="cd $HOME/Documents/'OX Drive'/'My files.localized'/Documents.localized/ams_documents"
alias amswik="cd $HOME/Documents/Obsidian/ams"

# macOS directories
alias desktop="cd $HOME/Desktop/"
alias downloads="cd $HOME/Downloads/"

# Obsidian directories
alias mind="cd $HOME/Documents/Obsidian/Mindmap"
alias notes="cd $HOME/Documents/Obsidian/Notes"
alias amsnotes="cd $HOME/Documents/Obsidian/ams"

## System alias
# - alias to fix crackling audio
# from: https://developer.apple.com/forums/thread/132423
alias fix-audio="xcrun simctl shutdown all && sudo killall coreaudiod"

## Applications
# Lazygit
alias lg="lazygit"

# Microsoft Teams
alias teams="open /Applications/'Microsoft Teams classic'.app --args -disable-features=HardwareMediaKeyHandling"

