#!/bin/zsh

### User's environment variables ###

# Set Zsh config directory
export ZDOTDIR="$HOME/.config/zsh"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# FZF
export FZF_DEFAULT_OPTS=" \
	--bind ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down `#add keybindings`							\
	--color gutter:-1,selected-bg:238 `#color configuration`													\
	--highlight-line `#highlight the whole current line`														\
	--marker ▏ `#multi-select marker`																			\
	--multi `#enable multi-select with tab/shift-tab`															\
	--pointer ▌ `#pointer to the current line`																	\
	--preview 'bat --style=numbers --color=always --line-range=:500 {}' `#specify a preview action to use bat`	\
	--prompt '▌ ' `#input prompt`																				\
"

# Lazygit configuration file
export LG_CONFIG_FILE="$HOME/.config/lazygit/config.yml"

# Atac configuration files
export ATAC_MAIN_DIR="$HOME/.config/atac/"
export ATAC_KEY_BINDINGS="$HOME/.config/atac/vim_key_bindings.toml"

# Set GHCup (Haskell) to use XDG specification folder
export GHCUP_USE_XDG_DIRS="true"

# Starship configuration files
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

